version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo "Checking current directory..."
      - echo %CD%
      - echo "Listing contents..."
      - dir
      - echo "Attempting to navigate to UserDetailsApp..."
      - IF EXIST UserDetailsApp (cd UserDetailsApp) ELSE (echo "Directory not found!" && exit /b 1)
      - echo "Restoring dependencies..."
      - dotnet restore

  build:
    commands:
      - echo "Building the project..."
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - "**/*"
  base-directory: UserDetailsApp\bin\Release  # Adjust if needed
