version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0 # Adjust the version based on your requirement
    commands:
      - echo Installing dependencies...
      - dotnet restore
  
  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - "**/*"
  base-directory: bin/Release
